Jabuti_apps/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [

    path('', include('autorizacao.urls')),

    path('admin/', admin.site.urls),

    path("veiculos/", include("veiculos.urls")),

    path("manutencao/", include("manutencao.urls")),

    path("autorizacao/", include("autorizacao.urls")),

    path("abastecimento/", include("abastecimento.urls")),

    path("agendamento/", include("agendamento.urls")),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

manutencao/urls.py
from django.urls import path
from . import views

urlpatterns = [

    path('', views.manutencao, name='manutencao'),
    path('criar-manutencao/', views.criar_manutencao, name='criar_manutencao'),
    path("update/<int:manutencao_id>/", views.update_manutencao, name="update_manutencao"),
    path("deletar/<int:manutencao_id>/", views.deletar_manutencao, name="deletar_manutencao"),
]

veiculos/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.veiculos, name='veiculos'),
    path("<int:veiculo_id>/", views.detalhe_veiculo, name="detalhe_veiculo"),
    path('cadastrar-veiculo/', views.cadastrar_veiculo, name='cadastrar_veiculo'),
    path("update/<int:veiculo_id>/", views.update_veiculo, name="update_veiculo"),
    path("deletar/<int:veiculo_id>/", views.deletar_veiculo, name="deletar_veiculo"),
    path('solicitar-manutencao/<int:veiculo_id>/', views.solicitar_manutencao, name='solicitar_manutencao'),
    path('criar-manutencao/<int:veiculo_id>/', views.criar_manutencao_veiculo, name='criar_manutencao_veiculo'),
]

manutencao/models.py
from datetime import timezone
from django.db import models

from veiculos.models import Veiculo

class Manutencao(models.Model):

    OPCOES_MANUTENCAO = [
        ('Troca de Oleo', 'Troca de Oleo'),
        ('Troca de Pneu', 'Troca de Pneu'),
        ('Troca Kit de Freio', 'Troca Kit de Freio'),
        ('Limpeza do radiador', 'Limpeza do radiador'),
        ('Outro', 'Outro'),
    ]

    veiculo = models.ForeignKey(Veiculo, on_delete=models.CASCADE)
    tipoManutencao = models.CharField(max_length=100, choices=OPCOES_MANUTENCAO, default=None)
    outraOpcao = models.CharField(max_length=100, blank=True, null=True)
    quilometragemDoVeiculo = models.FloatField()
    dataEntrada = models.DateField(blank=True, null=True)
    dataSaida = models.DateField(blank=True, null=True)
    criadoEm = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f'Manutenção: {self.tipoManutencao}'

veiculos/models.py
from django.db import models
from autorizacao.models import Orgao

class Veiculo(models.Model):

    OPCOES_GASOLINA = [
        ('Gasolina', 'Gasolina'),
        ('Gasolina/Alcool', 'Gasolina/Alcool'),
        ('Diesel', 'Diesel'),
        ('DieselS10', 'DieselS10'),
        ('Etanol', 'Etanol'),
    ]

    crv = models.BigIntegerField()
    cor = models.TextField()
    placa = models.TextField(max_length=7)
    marca = models.TextField()
    modelo = models.TextField()
    anoDeFabricacao = models.IntegerField()
    tipoDeCombustivel = models.CharField(max_length=100, choices=OPCOES_GASOLINA, default=None)
    capacidadeCombustivel = models.IntegerField()
    quilometragem = models.FloatField()
    estaDisponivel = models.BooleanField(default=True)
    precisaAbastecer = models.BooleanField(default=False)
    precisaDeManutencao = models.BooleanField(default=False)
    temSeguro  = models.BooleanField(default=None)
    alugado  = models.BooleanField(default=None)
    orgao = models.ForeignKey(Orgao, on_delete=models.DO_NOTHING, null=True, blank=True)
    ultimaLavagem = models.DateField(default=None, blank=True, null=True)
    criadoEm = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f'Modelo: {self.modelo}, Placa: {self.placa}'

manutencao/views.py
from datetime import date
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.messages import constants
from django.contrib import messages
from autorizacao.decorators import gestor_required
from manutencao.models import Manutencao
from veiculos.models import Veiculo

@gestor_required
def manutencao(request):
    orgao=request.user.orgao
    manutencoes = Manutencao.objects.filter(veiculo__orgao = orgao)
    hoje = date.today() 
    context = {
        'manutencoes': manutencoes,
        'hoje': hoje, 
    }
    return render(request, "manutencao.html", context)

@gestor_required
def criar_manutencao(request):
    veiculos_manutencao = Veiculo.objects.filter(precisaDeManutencao=True).filter(orgao=request.user.orgao)

    if request.method == 'POST':
        veiculo_id = request.POST.get('veiculo')
        tipo_manutencao = request.POST.get('tipo_manutencao')
        outra_opcao = request.POST.get('outra_opcao', '') 
        quilometragem = request.POST.get('quilometragem')
        dataEntrada = request.POST.get('dataEntrada')
        dataSaida = request.POST.get('dataSaida')
        
        Manutencao.objects.create(
            veiculo_id=veiculo_id,
            tipoManutencao=tipo_manutencao,
            outraOpcao=outra_opcao,
            quilometragemDoVeiculo=quilometragem,
            dataEntrada=dataEntrada,
            dataSaida=dataSaida
        )

        # Adiciona uma mensagem de sucesso
        messages.add_message(request, constants.SUCCESS, 'Manutenção cadastrada com sucesso.')

        # Redireciona de volta para a página de criação de manutenção
        return redirect('manutencao')

    return render(request, 'criar_manutencao.html', {"veiculos": veiculos_manutencao})

@gestor_required
def update_manutencao(request, manutencao_id):
    manutencao = get_object_or_404(Manutencao, id=manutencao_id)

    manutencao.dataEntrada = manutencao.dataEntrada.strftime('%Y-%m-%d')
    manutencao.dataSaida = manutencao.dataSaida.strftime('%Y-%m-%d')

    if request.method == 'POST':
        manutencao.veiculo.placa = request.POST.get('veiculo')
        manutencao.tipoManutencao = request.POST.get('tipo_manutencao')
        manutencao.outraOpcao = request.POST.get('outra_opcao', '')
        manutencao.quilometragemDoVeiculo = request.POST.get('quilometragem')
        manutencao.dataEntrada = request.POST.get('dataEntrada')
        manutencao.dataSaida = request.POST.get('dataSaida')


        manutencao.save()
        return redirect('manutencao')

    return render(request, 'update_manutencao.html', {"manutencao":manutencao})

@gestor_required
def deletar_manutencao(request, manutencao_id):
    manutencao = Manutencao.objects.get(id=manutencao_id)
    manutencao.delete()
    return redirect('manutencao')

manutencao/templates/criar_manutencao.html
{% extends 'base.html' %}

{% block content %}

            <main class="w-full flex-grow p-6">
                <div class="flex flex-wrap justify-center">
                    <div class="w-full lg:w-1/2 mt-6 pl-0 lg:pl-2 mx-auto">
                        <p class="text-xl pb-6 flex items-center">
                            <i class="fas fa-list mr-3"></i> Cadastrar manutenção
                        </p>
                        <div class="leading-loose">
                            <form method="POST" class="p-10 bg-white rounded shadow-xl">
                                {% csrf_token %}
                                
                                <div class="mt-2">
                                    <label for="id_veiculo" class="block text-sm text-gray-600">
                                        Veiculo:</label>
                                    <select id="id_veiculo" name="veiculo" 
                                    class="w-full h-12 px-2 py-2 text-gray-700 bg-gray-200 rounded">
                                        {% for veiculo in veiculos %}
                                            <option value="{{ veiculo.id }}">{{veiculo.marca}} {{veiculo.modelo}}/{{ veiculo.placa }}</option>
                                        {% endfor %}
                                    </select>
                                </div>

                                <div class="mt-2">
                                    <label for="tipo_manutencao" class="block text-sm text-gray-600">
                                        Tipo de Manutenção:</label>
                                    <select id="id_tipo_manutencao" name="tipo_manutencao" 
                                    class="w-full h-12 px-2 py-2 text-gray-700 bg-gray-200 rounded">
                                        <option value="Troca de Oleo" {% if manutencao.tipoManutencao == 'Troca de Oleo' %} selected {% endif %} >Troca de Óleo</option>
                                        <option value="Troca de Pneu" {% if manutencao.tipoManutencao == "Troca de Pneu" %} selected {% endif %}>Troca de Pneu</option>
                                        <option value="Troca Kit de Freio" {% if manutencao.tipoManutencao == "Troca Kit de Freio" %} selected {% endif %}>Troca Kit de Freio</option>
                                        <option value="Limpeza do radiador"{% if manutencao.tipoManutencao == "Limpeza do radiador" %} selected {% endif %}>Limpeza do radiador</option>
                                        <option value="Outro" {% if manutencao.tipoManutencao == "Outro"%} selected {% endif %} >Outro</option>
                                    </select>
                                </div>

                                <div class="mt-2">
                                    <label class="block text-sm text-gray-600" for="id_outra_opcao">Outra Opção:</label>
                                    <input class="w-full px-2 py-2 text-gray-700 bg-gray-200 rounded" id="id_outra_opcao" name="outra_opcao" type="number" value="{{ manutencao.outra_opcao }}" placeholder="Outra Opção:">
                                </div>

                                <div class="mt-2">
                                    <label class="block text-sm text-gray-600" for="id_quilometragem">Quilometragem:</label>
                                    <input class="w-full px-2 py-2 text-gray-700 bg-gray-200 rounded" id="id_quilometragem" name="quilometragem" type="number" value="{{ manutencao.quilometragemDoVeiculo }}" placeholder="Quilometragem">
                                </div>

                                <div class="mt-2">
                                    <label class="block text-sm text-gray-600" for="id_dataEntrada">Data Entrada:</label>
                                    <input class="w-full px-2 py-2 text-gray-700 bg-gray-200 rounded" id="id_dataEntrada" name="dataEntrada" type="date" value="{{ manutencao.dataEntrada }}" placeholder="Data Entrada">
                                </div>

                                <div class="mt-2">
                                    <label class="block text-sm text-gray-600" for="id_dataSaida">Data Saída:</label>
                                    <input class="w-full px-2 py-2 text-gray-700 bg-gray-200 rounded" id="id_dataSaida" name="dataSaida" type="date" value="{{ manutencao.dataSaida }}" placeholder="Data Saída">
                                </div>

                                <div class="mt-6 flex justify-center">
                                    <button class="px-4 py-2 text-white font-semibold tracking-wider bg-gray-900 rounded hover:bg-gray-800" type="submit" value="Cadastrar Manutenção">Cadastrar</button>
                                </div>
                            </form>
                        </div>
                    </div>
                    
                </div>
            </main>
{% endblock %}

manutencao/templates/manutencao.html
{% extends 'base.html' %}

{% block content %}
    
            <main class="w-full flex-grow p-6">
                <h1 class="text-3xl text-black pb-6">Manutenções</h1>
                <a href="{% url 'criar_manutencao' %}" class="flex items-center justify-center w-64 py-2 text-sm tracking-wide text-white transition-colors duration-200 bg-blue-500 rounded-lg  hover:bg-blue-600 dark:hover:bg-blue-500 dark:bg-blue-600">
                    <i class="fas fa-plus mr-3"></i>   
                    <span>Criar Manutenção</span>
                </a>
                <br>
                {% if messages %}
                    <br>
                    {% for message in messages %}
                        <section class="alert {{message.tags}}">
                            {{message}}
                        </section>
                    {% endfor %}
                {% endif %}
                <br>
                <hr>
                
                <div class="w-full mt-12"> 
                    <div class="bg-white overflow-auto">
                        <table class="text-left w-full border-collapse">
                            <thead>
                                <tr>
                                    <th class="py-4 px-6 bg-grey-lightest font-bold uppercase text-sm text-grey-dark border-b border-grey-light">Veiculo</th>
                                    <th class="py-4 px-6 bg-grey-lightest font-bold uppercase text-sm text-grey-dark border-b border-grey-light">Tipo Manutencao</th>
                                    <th class="py-4 px-6 bg-grey-lightest font-bold uppercase text-sm text-grey-dark border-b border-grey-light">Quilometragem</th>
                                    <th class="py-4 px-6 bg-grey-lightest font-bold uppercase text-sm text-grey-dark border-b border-grey-light">Entrada/Saida</th>
                                    <th class="py-4 px-6 bg-grey-lightest font-bold uppercase text-sm text-grey-dark border-b border-grey-light">Status</th>
                                    <th class="py-4 px-6 bg-grey-lightest font-bold uppercase text-sm text-grey-dark border-b border-grey-light">Ações</th>
                                </tr>
                            </thead>
                            <tbody>
                                <!-- Iterar sobre os veículos na página atual -->
                                {% for manutencao in manutencoes %}
                                <tr class="hover:bg-grey-lighter">
                                    <td class="py-4 px-6 border-b border-grey-light">{{ manutencao.veiculo.placa }}</td>
                                    <td class="py-4 px-6 border-b border-grey-light">{{ manutencao.tipoManutencao }} {% if manutencao.outraOpcao %}/ {{manutencao.outraOpcao}}{% endif %}</td>
                                    <td class="py-4 px-6 border-b border-grey-light">{{ manutencao.quilometragemDoVeiculo }}</td>
                                    <td class="py-4 px-6 border-b border-grey-light">{{ manutencao.dataEntrada }}/{{ manutencao.dataSaida }}</td>
                                    <td class="p-2 pr-12 border-b border-grey-light text-end">
                                        {% if manutencao.dataEntrada <= hoje and manutencao.dataSaida >= hoje %}
                                            <span class="text-center align-baseline inline-flex px-4 py-2 mr-auto items-center font-semibold text-[.95rem] leading-none text-yellow-800 bg-yellow-200 rounded-lg"> Em Andamento </span>
                                        {% elif manutencao.dataEntrada > hoje %}
                                            <span class="text-center align-baseline inline-flex px-4 py-2 mr-auto items-center font-semibold text-[.95rem] leading-none text-blue-800 bg-blue-200 rounded-lg"> Não Iniciada </span>
                                        {% else %}
                                            <span class="text-center align-baseline inline-flex px-4 py-2 mr-auto items-center font-semibold text-[.95rem] leading-none text-green-800 bg-green-200 rounded-lg"> Finalizada </span>
                                        {% endif %}
                                    </td>                                    
                                    
                                    <td class="py-4 px-6 border-b border-grey-light">
                                        <a href="{% url 'update_manutencao' manutencao.id %}" class="text-grey-lighter font-bold py-1 px-3 rounded text-xs bg-green hover:bg-green-dark"><button>Editar</button></a>
                                        <a href="{% url 'deletar_manutencao' manutencao.id %}" class="text-grey-lighter font-bold py-1 px-3 rounded text-xs bg-red hover:bg-red-dark"><button>Deletar</button></a>
                                    </td>
                                </tr>
                                {% endfor %}
                            </tbody>
                        </table>
                    </div>
                   <!-- Exibição de página -->
            <div class="flex items-center justify-between mt-6">
                <!-- Link para a página anterior -->
                <a href="{% if page_obj.has_previous %}?page={{ page_obj.previous_page_number }}{% endif %}" class="flex items-center px-5 py-2 text-sm text-gray-700 capitalize transition-colors duration-200 bg-white border rounded-md gap-x-2 hover:bg-gray-100 dark:bg-gray-900 dark:text-gray-200 dark:border-gray-700 dark:hover:bg-gray-800">
                    <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="w-5 h-5 rtl:-scale-x-100">
                        <path stroke-linecap="round" stroke-linejoin="round" d="M6.75 15.75L3 12m0 0l3.75-3.75M3 12h18" />
                    </svg>

                    <span>
                        previous
                    </span>
                </a>

                <!-- Números de página -->
                <div class="items-center hidden md:flex gap-x-3">
                    {% for num in page_obj.paginator.page_range %}
                        <a href="?page={{ num }}" class="px-2 py-1 text-sm {% if page_obj.number == num %}text-blue-500{% else %}text-gray-500 hover:bg-gray-100 dark:hover:bg-gray-800 dark:text-gray-300{% endif %} rounded-md {% if page_obj.number == num %}bg-blue-100/60{% endif %}">{{ num }}</a>
                    {% endfor %}
                </div>

                <!-- Link para a próxima página -->
                <a href="{% if page_obj.has_next %}?page={{ page_obj.next_page_number }}{% endif %}" class="flex items-center px-5 py-2 text-sm text-gray-700 capitalize transition-colors duration-200 bg-white border rounded-md gap-x-2 hover:bg-gray-100 dark:bg-gray-900 dark:text-gray-200 dark:border-gray-700 dark:hover:bg-gray-800">
                    <span>
                        Next
                    </span>

                    <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="w-5 h-5 rtl:-scale-x-100">
                        <path stroke-linecap="round" stroke-linejoin="round" d="M17.25 8.25L21 12m0 0l-3.75 3.75M21 12H3" />
                    </svg>
                </a>
            </div>
        </div>
    </main>
    
{% endblock %}

manutencao/templates/update_manutencao.html
{% extends 'base.html' %}

{% block content %}

            <main class="w-full flex-grow p-6">
                <div class="flex flex-wrap justify-center">
                    <div class="w-full lg:w-1/2 mt-6 pl-0 lg:pl-2 mx-auto">
                        <p class="text-xl pb-6 flex items-center">
                            <i class="fas fa-list mr-3"></i> Editar Manutenção
                        </p>
                        <div class="leading-loose">
                            <form action="{% url 'update_manutencao' manutencao.id %}" method="POST" class="p-10 bg-white rounded shadow-xl">
                                {% csrf_token %}
                                <div class="mt-2">
                                    <label for="id_veiculo" class="block text-sm text-gray-600">
                                        Veiculo:</label>
                                    <select id="id_veiculo" name="veiculo" 
                                    class="w-full h-12 px-2 py-2 text-gray-700 bg-gray-200 rounded">
                                            <option value="{{ veiculo.id }}">{{ manutencao.veiculo.placa }}</option>
                                            
                                    </select>
                                </div>

                                <div class="w-full inline-grid grid-cols-2 gap-x-4 mt-2">
                                    <div>
                                        <label for="tipo_manutencao" class="block text-sm text-gray-600">
                                            Tipo de Manutenção:</label>
                                        <select id="id_tipo_manutencao" name="tipo_manutencao" 
                                        class="w-full h-12 px-2 py-2 text-gray-700 bg-gray-200 rounded">
                                            <option value="Troca de Oleo" {% if manutencao.tipoManutencao == 'Troca de Oleo' %} selected {% endif %} >Troca de Óleo</option>
                                            <option value="Troca de Pneu" {% if manutencao.tipoManutencao == "Troca de Pneu" %} selected {% endif %}>Troca de Pneu</option>
                                            <option value="Troca Kit de Freio" {% if manutencao.tipoManutencao == "Troca Kit de Freio" %} selected {% endif %}>Troca Kit de Freio</option>
                                            <option value="Limpeza do radiador"{% if manutencao.tipoManutencao == "Limpeza do radiador" %} selected {% endif %}>Limpeza do radiador</option>
                                            <option value="Outro" {% if manutencao.tipoManutencao == "Outro"%} selected {% endif %} >Outro</option>
                                        </select>
                                    </div>
                                </div>                                                              

                                <div class="mt-2">
                                    <label class="block text-sm text-gray-600" for="id_outra_opcao">Outra Opção:</label>
                                    <input class="w-full px-2 py-2 text-gray-700 bg-gray-200 rounded" id="id_outra_opcao" name="outra_opcao" type="text" value="{{ manutencao.outraOpcao }}" placeholder="Outra Opção">
                                </div>

                                <div class="mt-2">
                                    <label class="block text-sm text-gray-600" for="id_quilometragem">Quilometragem:</label>
                                    <input class="w-full px-2 py-2 text-gray-700 bg-gray-200 rounded" id="id_quilometragem" name="quilometragem" type="number" value="{{ manutencao.quilometragemDoVeiculo }}">
                                </div>

                                <div class="mt-2">
                                    <label class="block text-sm text-gray-600" for="id_dataEntrada">Data Entrada:</label>
                                    <input class="w-full px-2 py-2 text-gray-700 bg-gray-200 rounded" id="id_dataEntrada" name="dataEntrada" type="date" value="{{ manutencao.dataEntrada }}">
                                </div>

                                <div class="mt-2">
                                    <label class="block text-sm text-gray-600" for="id_dataSaida">Data Saída:</label>
                                    <input class="w-full px-2 py-2 text-gray-700 bg-gray-200 rounded" id="id_dataSaida" name="dataSaida" type="date" value="{{ manutencao.dataSaida }}" >
                                </div>

                                <div class="mt-6 flex justify-center">
                                    <button class="px-4 py-2 text-white font-semibold tracking-wider bg-gray-900 rounded hover:bg-gray-800" type="submit">Salvar alterações</button>
                                </div>
                            </form>
                        </div>
                    </div>
                    
                </div>
            </main>

{% endblock %}